<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Client extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Client_model');
    } 

    /*
     * Listing of clients
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('client/index?');
        $config['total_rows'] = $this->Client_model->get_all_clients_count();
        $this->pagination->initialize($config);

        $data['clients'] = $this->Client_model->get_all_clients($params);
        
        $data['_view'] = 'client/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new client
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('email','Email','valid_email');
		$this->form_validation->set_rules('noms_complet','Noms Complet','required');
		$this->form_validation->set_rules('email','Email','is_unique[tb_dgi_clients.email]|valid_email');
        $this->form_validation->set_rules('telephone','telephone','is_unique[tb_dgi_clients.telephone]');

		if($this->form_validation->run())     
        {   
            $params = array(
				'noms_complet' => $this->input->post('noms_complet'),
				'telephone' => $this->input->post('telephone'),
				'email' => $this->input->post('email'),
				'profession' => $this->input->post('profession'),
				'adresse' => $this->input->post('adresse'),
                'client_code' => $this->input->post('code'),
            );
            
            $client_id = $this->Client_model->add_client($params);
            redirect('client/index');
        }
        else
        {            
            $data['_view'] = 'client/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a client
     */
    function edit($client_id)
    {   
        // check if the client exists before trying to edit it
        $data['client'] = $this->Client_model->get_client($client_id);
        
        if(isset($data['client']['client_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('email','Email','valid_email');
			$this->form_validation->set_rules('noms_complet','Noms Complet','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'noms_complet' => $this->input->post('noms_complet'),
					'telephone' => $this->input->post('telephone'),
					'email' => $this->input->post('email'),
					'profession' => $this->input->post('profession'),
					'adresse' => $this->input->post('adresse'),
                );

                $this->Client_model->update_client($client_id,$params);            
                redirect('client/index');
            }
            else
            {
                $data['_view'] = 'client/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The client you are trying to edit does not exist.');
    } 

    /*
     * Deleting client
     */
    function remove($client_id)
    {
        $client = $this->Client_model->get_client($client_id);

        // check if the client exists before trying to delete it
        if(isset($client['client_id']))
        {
            $this->Client_model->delete_client($client_id);
            redirect('client/index');
        }
        else
            show_error('The client you are trying to delete does not exist.');
    }
    
}
