<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Vehicule extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Vehicule_model');
    } 

    /*
     * Listing of vehicules
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('vehicule/index?');
        $config['total_rows'] = $this->Vehicule_model->get_all_vehicules_count();
        $this->pagination->initialize($config);

        $data['vehicules'] = $this->Vehicule_model->get_all_vehicules($params);
        
        $data['_view'] = 'vehicule/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new vehicule
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'client_sid' => $this->input->post('client_sid'),
				'chasis' => $this->input->post('chasis'),
				'num_plaque' => $this->input->post('num_plaque'),
				'marque_vehicule' => $this->input->post('marque_vehicule'),
				'type_vehicule' => $this->input->post('type_vehicule'),
				'poids_vehicule' => $this->input->post('poids_vehicule'),
				'couleur_vehicule' => $this->input->post('couleur_vehicule'),
				'nombre_place_passagers' => $this->input->post('nombre_place_passagers'),
				'annee_fabrication_vehicule' => $this->input->post('annee_fabrication_vehicule'),
				'type_pays_provenance' => $this->input->post('type_pays_provenance'),
            );
            
            $vehicule_id = $this->Vehicule_model->add_vehicule($params);
            redirect('vehicule/index');
        }
        else
        {
			$this->load->model('Client_model');
			$data['all_clients'] = $this->Client_model->get_all_clients();
            
            $data['_view'] = 'vehicule/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a vehicule
     */
    function edit($vehicule_id)
    {   
        // check if the vehicule exists before trying to edit it
        $data['vehicule'] = $this->Vehicule_model->get_vehicule($vehicule_id);
        
        if(isset($data['vehicule']['vehicule_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'client_sid' => $this->input->post('client_sid'),
					'chasis' => $this->input->post('chasis'),
					'num_plaque' => $this->input->post('num_plaque'),
					'marque_vehicule' => $this->input->post('marque_vehicule'),
					'type_vehicule' => $this->input->post('type_vehicule'),
					'poids_vehicule' => $this->input->post('poids_vehicule'),
					'couleur_vehicule' => $this->input->post('couleur_vehicule'),
					'nombre_place_passagers' => $this->input->post('nombre_place_passagers'),
					'annee_fabrication_vehicule' => $this->input->post('annee_fabrication_vehicule'),
					'type_pays_provenance' => $this->input->post('type_pays_provenance'),
                );

                $this->Vehicule_model->update_vehicule($vehicule_id,$params);            
                redirect('vehicule/index');
            }
            else
            {
				$this->load->model('Client_model');
				$data['all_clients'] = $this->Client_model->get_all_clients();

                $data['_view'] = 'vehicule/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The vehicule you are trying to edit does not exist.');
    } 

    /*
     * Deleting vehicule
     */
    function remove($vehicule_id)
    {
        $vehicule = $this->Vehicule_model->get_vehicule($vehicule_id);

        // check if the vehicule exists before trying to delete it
        if(isset($vehicule['vehicule_id']))
        {
            $this->Vehicule_model->delete_vehicule($vehicule_id);
            redirect('vehicule/index');
        }
        else
            show_error('The vehicule you are trying to delete does not exist.');
    }
    
}
