<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Client_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get client by client_id
     */
    function get_client($client_id)
    {
        return $this->db->get_where('tb_dgi_clients',array('client_id'=>$client_id))->row_array();
    }
    function get_client_number($client_code)
    {
        return $this->db->get_where('tb_dgi_clients',array('client_code'=>$client_code))->row_array();
    }
    
    /*
     * Get all clients count
     */
    function get_all_clients_count()
    {
        $this->db->from('tb_dgi_clients');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all clients
     */
    function get_all_clients($params = array())
    {
        $this->db->order_by('client_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_dgi_clients')->result_array();
    }
        
    /*
     * function to add new client
     */
    function add_client($params)
    {
        $this->db->insert('tb_dgi_clients',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update client
     */
    function update_client($client_id,$params)
    {
        $this->db->where('client_id',$client_id);
        return $this->db->update('tb_dgi_clients',$params);
    }
    
    /*
     * function to delete client
     */
    function delete_client($client_id)
    {
        return $this->db->delete('tb_dgi_clients',array('client_id'=>$client_id));
    }
}
