<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fiche_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fiche by fiche_id
     */
    function get_fiche($fiche_id)
    {
        return $this->db->get_where('tb_dgi_fiches',array('fiche_id'=>$fiche_id))->row_array();
    }
    
    /*
     * Get all fiches count
     */
    function get_all_fiches_count()
    {
        $this->db->from('tb_dgi_fiches');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all fiches
     */
    function get_all_fiches($params = array())
    {
        $this->db->order_by('fiche_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $this->db->join('tb_dgi_clients', 'tb_dgi_clients.client_id = tb_dgi_fiches.client_sid');
        return $this->db->get('tb_dgi_fiches')->result_array();
    }
        
    /*
     * function to add new fiche
     */
    function add_fiche($params)
    {
        $this->db->insert('tb_dgi_fiches',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fiche
     */
    function update_fiche($fiche_id,$params)
    {
        $this->db->where('fiche_id',$fiche_id);
        return $this->db->update('tb_dgi_fiches',$params);
    }
    
    /*
     * function to delete fiche
     */
    function delete_fiche($fiche_id)
    {
        return $this->db->delete('tb_dgi_fiches',array('fiche_id'=>$fiche_id));
    }
}
