<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Note_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get note by note_id
     */
    function get_note($note_id)
    {
        return $this->db->get_where('tb_dgi_notes',array('note_id'=>$note_id))->row_array();
    }
    
    /*
     * Get all notes count
     */
    function get_all_notes_count()
    {
        $this->db->from('tb_dgi_notes');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all notes
     */
    function get_all_notes($params = array())
    {
        $this->db->order_by('note_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $this->db->join('tb_dgi_fiches', 'tb_dgi_fiches.fiche_id = tb_dgi_notes.fiche_sid');
        $this->db->join('tb_dgi_clients', 'tb_dgi_clients.client_id = tb_dgi_fiches.client_sid');
        return $this->db->get('tb_dgi_notes')->result_array();
    }
        
    /*
     * function to add new note
     */
    function add_note($params)
    {
        $this->db->insert('tb_dgi_notes',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update note
     */
    function update_note($note_id,$params)
    {
        $this->db->where('note_id',$note_id);
        return $this->db->update('tb_dgi_notes',$params);
    }
    
    /*
     * function to delete note
     */
    function delete_note($note_id)
    {
        return $this->db->delete('tb_dgi_notes',array('note_id'=>$note_id));
    }
}
