<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Paiement_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get paiement by paiement_id
     */
    function get_paiement($paiement_id)
    {
        return $this->db->get_where('tb_dgi_paiements',array('paiement_id'=>$paiement_id))->row_array();
    }
    
    /*
     * Get all paiements count
     */
    function get_all_paiements_count()
    {
        $this->db->from('tb_dgi_paiements');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all paiements
     */
    function get_all_paiements($params = array())
    {
        $this->db->order_by('paiement_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        $this->db->join('tb_dgi_notes', 'tb_dgi_notes.note_id = tb_dgi_paiements.numero_note_sid');
        $this->db->join('tb_dgi_clients', 'tb_dgi_clients.client_id = tb_dgi_paiements.client_sid');
        return $this->db->get('tb_dgi_paiements')->result_array();
    }
        
    /*
     * function to add new paiement
     */
    function add_paiement($params)
    {
        $this->db->insert('tb_dgi_paiements',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update paiement
     */
    function update_paiement($paiement_id,$params)
    {
        $this->db->where('paiement_id',$paiement_id);
        return $this->db->update('tb_dgi_paiements',$params);
    }
    
    /*
     * function to delete paiement
     */
    function delete_paiement($paiement_id)
    {
        return $this->db->delete('tb_dgi_paiements',array('paiement_id'=>$paiement_id));
    }
}
